export const SET_EXPERIENCE_DATA = 'SET_EXPERIENCE_DATA';
export const SET_PROJECTS_DATA = 'SET_PROJECTS_DATA';
export const SET_TECHSKILLS_DATA = 'SET_TECHSKILLS_DATA';
export const SET_DEVTOOLS_DATA = 'SET_DEVTOOLS_DATA';
export const SET_RESUME_DATA = 'SET_RESUME_DATA';